#https://www.lendingclub.com/developers/listed-loans.action

# System configuration
library(shiny)
library(shinyBS)
library(gtools)
library(dplyr)
require(rCharts)
library(reshape2)

error <- 0

path <- '/usr/bin/chromium-browser'
# Change working directory
if ( file.exists('/home/john') ) {
  setwd("/home/john/Dropbox/pls")
} else if ( file.exists('/home/user') ) {
  setwd("/home/user/pls")
} else {
  setwd("C:/Users/john/Dropbox/pls")
  path <- file.path('C:','Program Files (x86)','Google','Chrome','Application','chrome.exe')
}

if(!exists('notes')) {
  load('data/filterNotes.rda')
}

if(!exists('apiFields')) {
  apiFields=read.csv('data/apiFields.csv',sep='|')
}

# Obtain total number of notes
totalNotes=nrow(notes)
filterStr <- ''
filterStrProd <- ''

if (file.exists('config/filter.rda')) {
  load('config/filter.rda')
} else {
  filter <- list()
}

# Number formatter function
printNumber <- function(value, digits=0, sep=",", decimal=".") {
  formatC(value, format = "f", big.mark = sep, digits=digits, decimal.mark=decimal)
}

# Browser launch settings
launch.browser = function(appUrl, browser.path=path) {
  system(sprintf('"%s" --disable-gpu --app="data:text/html,<html>
    <head>
    <title>Custom Filter</title>
    </head>
    <body>
    <script>window.resizeTo(1050,700);window.location=\'%s\';</script>
    </body></html>" &', browser.path, appUrl))
}

help <- function() {
return('
<p>Peer Lending Server provides artificial intelligence, demographics, custom fields, 
historical analytics, and projected returns to create create a powerful and evidence based 
filter.  The side panel contains fields available 
from Lending Club as well as fields automatically
generated by PLS. You can hover your mouse over a field label for more information regarding
the field.  You can also hover your mouse over numeric input fields for information
regarding the minimum and maximum historical values.
</p>
<li><b>Common:</b> Most popular fields used by Lending Club investors
<li><b>Credit History:</b> Borrower credit information
<li><b>Loan Detail:</b> Specific loan information
<li><b>About Borrower:</b> Miscellaneous borrower information
<li><b>Custom:</b> Fields automatically generated for new and historical notes.
<li><b>Preset Filters:</b> Pre-made example filters.
<li><b>Completed Notes Only:</b> Check the box to view historical information
for completed notes only.  Completed notes are notes that have either been
fully paid or charged off.  In addition, they are fully mature having aged to
there full term length to avoid artificially deflating
return.  For example, including notes that have charged off before maturity
would not be balanced by future fully paid notes with the same month of origination.
<br><br>
<p>
<p>
Historical analytics data in the main panel provides a snapshot of historical
notes that match the filter criteria:
</p>
<li><b>Total Notes:</b> Total available historical notes
<li><b>Filtered Notes:</b> Total historical notes matching filter criteria
<li><b>Filtered Percent:</b> Percent of notes filtered
<li><b>Instant ROI:</b> Instantaneous Return on Investment (iROI) without discounting potential future loss. The
internal rate of return is calculated using actual borrower payment history for each note.
PLS performs an XIRR calculation using its actual payment history for each historical note. 
<li><b>Projected Return:</b> Projected Return on Investment.  PLS uses a statistical model
to generate a probability curve of future payments.  Using a historical statistical model, 
PLS calculates the XIRR for each note using actual and projected payments. This provides
a more realistic projected ROI versus iROI. 
<li><b>Age Months:</b> Average age in months
<li><b>Default Percent:</b>
<li><b>Late 16:</b>
<li><b>Late 31:</b>




')
}


resetInputs <- function (session,inputs) {
  closeAlert(session, alertId="a1")
  for (name in names(inputs)) {
    if(invalid(inputs[[name]])) {
      next()
    }
    if (grepl('(Min$|Max$|model|customFilter)', name)) {
      updateNumericInput(session, name, value = '')
    } else {
      choices <- eval(parse(text=paste(name,'Choices',sep='')))
      updateSelectizeInput(session, name, choices=choices, selected='')
    }
  }
}


buttonSaveValue <- 0
buttonResetValue <- 0
buttonfilterSocialLender <- 0
buttonfilterBalancedROI <- 0
buttonApplyCustomFilter <- 0
initFilter <- 0

fn <- ''
customFilterStr <- ''

numInput<-function (Id, value = "", label='', ...) {
  div(style="display:inline-block",
    tags$label(label,`for` = Id),
    numericInput(inputId = Id, label='', value = filter[[Id]], ...))
}

panel <- function (title,text) {
  div(class="panel panel-default",
    div(class="panel-heading",
      title
    ),
    div(class="panel-body",
      text
    )
  )
}


toolTipMin <- function(id,nas=0) {
  if(nas) {
    msg=paste('Historical min: ',min(notes[[id]],na.rm=TRUE),'Percent NA\'s: ',nas,sep='')
  } else {
    msg=paste('Historical min: ',min(notes[[id]],na.rm=TRUE), sep='')
  }
  bsTooltip(id = paste(id,'Min',sep=''), msg, 
    placement = "bottom", trigger = "hover")
}
toolTipMax <- function(id,nas=0) {
  bsTooltip(id = paste(id,'Max',sep=''), title = paste('Historical max:',max(notes[[id]],na.rm=TRUE)), 
    placement = "bottom", trigger = "hover")
}
setName <- function(str) {
  fn<<-str
  return(NULL)
}

strChop <- function(str,num=50) {
  if ( length(str) > num ) {
    paste(substr(str,1,num),"...",sep="")
  } else {
    str
  }
}

termChoices <- c('36','60')
gradeChoices <- levels(notes$grade)
purposeChoices <- levels(notes$purpose)
homeOwnershipChoices <- levels(notes$homeOwnership)
subGradeChoices <- levels(notes$subGrade)
initialListStatusChoices <- levels(notes$initialListStatus)
addrStateChoices <- levels(notes$addrState)
empLengthChoices <- sort(unique(notes$empLength))
isIncVChoices <- levels(notes$isIncV)
completeChoices <- c(TRUE,FALSE)
reviewStatusSpecChoices <- c('APPROVED','NOT_APPROVED')
apiFieldChoices <- paste(apiFields$Field,apiFields$Description,sep=": ")

shinyApp(
  ui = fluidPage(
    tags$style(type="text/css", 'label {
      display: block;
    }'),
    tags$style(type="text/css", '.nomar {
      margin-bottom: 0px;
    }'),
    tags$style(type="text/css", '[id$="Max"] {width: 100px;}'),
    tags$style(type="text/css", '[id$="Min"] {
                width: 100px;
                display: inline-block;
                margin-bottom: 5px;
               }'),
    fluidRow(
      br()
    ),
    fluidRow(
      column(4,
        wellPanel(  
          bsCollapse(multiple = TRUE, open = NULL, id = "collapse1",
            
            
            bsCollapsePanel("Common", 
   
              selectInput('term', 'Loan Term', 
                choices=termChoices,
                multiple = TRUE,
                selected = filter$term,
                selectize = TRUE),
              
              selectInput('grade', 'Grade', 
                choices=gradeChoices,
                multiple = TRUE,
                selected = filter$grade,
                selectize = TRUE),
              
              setName('intRate'),
                tags$label("Interest Rate",class='control-label nomar'),
                numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
                numInput(paste(fn,'Max',sep=''), step=1),br(),
                toolTipMin(fn,round(mean(is.na(notes[[fn]])))),
                toolTipMax(fn),

              selectInput('purpose', 'Purpose', 
                choices=purposeChoices,
                multiple = TRUE,
                selected = filter$purpose,
                selectize = TRUE),
              
              selectInput('homeOwnership', 'Home Ownership', 
                choices=homeOwnershipChoices,
                multiple = TRUE,
                selected = filter$homeOwnership,
                selectize = TRUE),

              setName('loanAmount'),
              tags$label("Loan Amount",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('pubRec'),
              tags$label("Derogatory Public Records",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
            
              setName('inqLast6Mths'),
              tags$label("Inquiries Last 6 Months",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),

              setName('delinq2Yrs'),
              tags$label("Delinquencies Last 2 Years",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('dti'),
              tags$label("Debt to Income Ratio",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('revolUtil'),
              tags$label("Revolving Line Utilization",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('ficoRangeHigh'),
              tags$label("FICO Range High",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              
              # End of Panel
              value="test1"),
            
            
            
            ### Credit History
            bsCollapsePanel("Credit History",

              setName('mthsSinceLastDelinq'),
              tags$label("Months Since Last Delinquency",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('mthsSinceLastRecord'),
              tags$label("Months Since Last Public Record",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),

              setName('openAcc'),
              tags$label("Number of Open Credit Lines",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('revolBal'),
              tags$label("Total Credit Revolving Balance",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('totalAcc'),
              tags$label("Number of Credit Lines",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('mthsSinceLastMajorDerog'),
              tags$label("Months Since Last Major Derogatory",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),

              setName('collections12MthsExMed'),
              tags$label("1 Year Collections Except Medical",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('ficoRangeLow'),
              tags$label("FICO Range Low",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
                          
              
              # End of panel
              value="test2"),
            
            
            
            ### Loan Detail
            bsCollapsePanel("Loan Detail",
              
              
              selectInput('subGrade', 'Sub Grade', 
                choices=subGradeChoices,
                multiple = TRUE,
                selected = filter$subGrade,
                selectize = TRUE),
              

              selectInput('initialListStatus', 'Initial List Status', 
                choices=initialListStatusChoices,
                multiple = TRUE,
                selected = filter$initialListStatus,
                selectize = TRUE),
              
              setName('installment'),
              tags$label("Installment Amount",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              # End of Panel
              value="test3"),
            
            
            ### About Borrower
            bsCollapsePanel("About Borrower",

              selectInput('addrState', 'State', 
                choices=addrStateChoices,
                multiple = TRUE,
                selected = filter$addrState,
                selectize = TRUE),

              
              selectInput('empLength', 'Employment Length', 
                choices=empLengthChoices,
                multiple = TRUE,
                selected = filter$empLength,
                selectize = TRUE),

     
            
              selectInput('isIncV', 'Is Income Verified', 
                choices=isIncVChoices,
                multiple = TRUE,
                selected = filter$isIncV,
                selectize = TRUE),
              
              setName('annualInc'),
              tags$label("Annual Income",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              
              # End of Panel
              value="test4"),

            bsCollapsePanel("Custom",
              
              div(
                icon("info-circle"),
                tags$caption("Fields generated by PLS")
              ),br(),
              
              setName('model'),
              tags$label("Artificial Intelligence Model",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              
              setName('earliestCrLineMonths'),
              tags$label("Earliest Credit Line Months",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('installmentIncomeRatio'),
              tags$label("Installment Income Ratio",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('revolBalAnnualIncRatio'),
              tags$label("Revolving Balance Income Ratio",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('ficoInstallmentRatio'),
              tags$label("FICO Installment Ratio",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('dtiInstallmentRatio'),
              tags$label("DTI Installment Ratio",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('avgWage'),
              tags$label("Average Wage of Zip Code",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('avgWageIncRatio'),
              tags$label("Average Wage Income",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
              setName('population'),
              tags$label("Population of Zip Code",class='control-label nomar'),
              numInput(paste(fn,'Min',sep=''), step=1), "  to  ",
              numInput(paste(fn,'Max',sep=''), step=1),br(),p(),
              toolTipMin(fn),
              toolTipMax(fn),
              
             
              # End of Panel
              value="test5"),
            
#             bsCollapsePanel("New Fields",
#               
#                             
#              div(
#                icon("info-circle"),
#                tags$caption("Recently added fields to Lending Club API.  These fields have very limited
#                   historical data.")
#              ),br(),              
#                             
#               selectInput('completed', 'Completed Notes -', 
#                 choices=completeChoices,
#                 multiple = TRUE,
#                 selected = filter$complete,
#                 selectize = TRUE),
#               
#               
#               setName('expDefaultRate'),
#               "Expected Default Rate *", br(),
#               numInput(paste(fn,'MinNonfilter',sep=''), step=.1), "  to  ",
#               numInput(paste(fn,'MaxNonfilter',sep=''), step=.1),
#             
#               selectInput('reviewStatusSpec', 'Review Status *', 
#                 choices=reviewStatusSpecChoices,
#                 multiple = TRUE,
#                 selected = filter$reviewStatusNonfilter,
#                 selectize = TRUE),
#               
#               setName('investorCount'),
#               "Investor Count *", br(),
#               numInput(paste(fn,'MinNonfilter',sep=''), step=1), "  to  ",
#               numInput(paste(fn,'MaxNonfilter',sep=''), step=1),
#               
#               
#               # End of Panel
#               value="test6"),
#             
            
            
            bsCollapsePanel("Preset Filters",
              
              div(
                icon("info-circle"),
                tags$caption("Under constsuction")
              ),br(), 
                 
              actionButton('filterSocialLender', 'Social Lender'),
              actionButton('filterBalancedROI', 'Balanced ROI'),

              
              # End of Panel
              value="test7")
          ),
          checkboxInput('complete', 'Completed Notes Only', value = FALSE)
        ),
        column(12,
          fluidRow(
            actionButton('save', 'Save'),
            actionButton("reset", "Clear"),
            actionButton("help", "Help"),
            tags$button( "Close", id="close", type="button", class="btn action-button", onclick="self.close()")
          ),
          fluidRow(
            br(),
            bsAlert("alert"),
            bsModal("helper", "Custom Filter", "help", size = "large",
              HTML(help())
            )
          )
        )
      ),
      column(8,
  
 
        bsCollapse(id = "main", open = "Historical Filter Analysis", multiple=TRUE,
           bsCollapsePanel("Custom Filter - Expert Use Only", style = "warning",
              p("Some fields are not included in the left side bar for reasons such as lack of historical
                data and minimal usefulness.  Append a custom filter below using any LC API field."),
              
             selectInput('apiField', 'Lending Club API Fields (Reference Only)', 
                choices=c(" ",apiFieldChoices),
                selected=' ',
                width='100%',
                multiple = FALSE,
                selectize = TRUE),
             
              div(tags$textarea(style="width: 100%", rows=10, id="customFilter", filter$customFilter)),
              div(actionButton("applyCustomFilter", "Apply Custom Filter"))
           ), 
           bsCollapsePanel("Historical Filter Analysis",
             column(12,
               uiOutput("criteria"),
               strong(textOutput('text')),
               uiOutput('summary'),
               showOutput("gaugeROI", "highcharts"),
               showOutput("roi", "highcharts"),
               showOutput("count", "highcharts")
             )
           )

        )
        
        

      )

    )
  ), 
  ############################################################################################################
  server = function(input, output, session) {
    
    session$onSessionEnded(function() {
      stopApp()
    })
    observe({
      if(input$save > buttonSaveValue) {
        buttonSaveValue <<- input$save
                
        closeAlert(session, alertId="a1")
        
        # Save configuration data
        filter <- reactiveValuesToList(input)
                
        if(filterStrProd == 'intRate > 0') {
          createAlert(session,"alert", alertId="a1", 
                      content="Error: Empty filter",
                      style = "danger",
            append = FALSE)
          return()
        }
        
                        
        if(error != 0) {
          createAlert(session,"alert", alertId="a1", 
                      content="Error: Invalid filter",
                      style = "danger",
            append = FALSE)
          return()
        }
        
        # print(filterStrProd)
        save(filter,filterStrProd,file='config/filter.rda')
        
        createAlert(session, anchorId = "alert", alertId="a1", 
          content="Configuration saved",
          style = "success",
          append = FALSE)
        
      }
    })
    
    # Reset button
    observe({
      if(input$reset > buttonResetValue) {
        buttonResetValue <<- input$reset
        resetInputs(session,inputs)
        customFilterStr<<-''
        #updateNumericInput(session, "intRateMin", value = '')
      } 
    })
    
    # Save custom filter button
    observe({
      if(input$applyCustomFilter > buttonApplyCustomFilter) {
        buttonApplyCustomFilter <<- input$applyCustomFilter
        if (input$customFilter != ''){ 
          customFilterStr <<- gsub("[\r\n]", "", input$customFilter)
        } else {
          customFilterStr <<- ''
        }
      } 
    }, priority=100)
    
    observe({
      if(input$filterSocialLender > buttonfilterSocialLender) {
        buttonfilterSocialLender <<- input$filterSocialLender
        resetInputs(session,inputs)
        updateNumericInput(session, "intRateMin", value = '14')
        updateNumericInput(session, "delinq2YrsMax", value = '0')
        updateNumericInput(session, "installmentIncomeRatioMax", value = '15')
        updateNumericInput(session, "modelMin", value = '85')
        updateNumericInput(session, "pubRecMax", value = '0')
        updateNumericInput(session, "inqLast6MthsMax", value = '2')
        updateSelectInput(session, 'grade', selected = c('B','C','D','E'))
#         updateSelectInput(session, 'purpose', selected = c("credit_card", "debt_consolidation", "car", 
#           "home_improvement", "educational", "house", "moving", "other", "renewable_energy", "major_purchase", 
#           "vacation", "wedding"))
        # updateSelectInput(session, 'empLength', selected = c('12','24','36','48','60','72','84','96','108','120'))
      } 
    })
    
    observe({
      if(input$filterBalancedROI > buttonfilterBalancedROI) {
        buttonfilterBalancedROI <<- input$filterBalancedROI
        resetInputs(session,inputs)
        updateSelectInput(session, 'grade', selected = c('B','C','D'))
        updateNumericInput(session, "delinq2YrsMax", value = '0')
        updateNumericInput(session, "pubRecMax", value = '0')
        updateNumericInput(session, "modelMin", value = '90')
        updateNumericInput(session, "earliestCrLineMonthsMin", value = '120')
        updateNumericInput(session, "collections12MthsExMedMax", value = '0')
        updateSelectInput(session, 'empLength', selected = c('12','24','36','48','60','72','84','96','108','120'))
      } 
    })
    
    dataInput <- reactive({
      

      # Dynamically obtain field names UI input
      inputsRaw <<- reactiveValuesToList(input)
      nNotes <<- c(names(notes),'customFilter')
      nMin <<- paste(nNotes, "Min", sep="")
      nMax <<- paste(nNotes, "Max", sep="")
      nAll <<- c(nNotes,nMin,nMax)
      inputs <<- inputsRaw[names(inputsRaw) %in% nAll]
      
      filterStr <<- ''
      filterStrProd <<- ''
      for (name in names(inputs)) {
        if(invalid(inputs[[name]])) {
          # print('nope')
          next()
        }
        # print(name)
        if (name == 'complete') {
          # print(input$complete)
          if(input$complete==FALSE) next
          field <- name
          # expr <- paste(field,'%in%',deparse(as.logical(inputs[[name]])))
          filterStr <<- paste(filterStr,'(complete==TRUE & (loan_status=="Fully_Paid" | loan_status=="Charged_Off"))',sep=' & ')
          # print(filterStr)
        } else if (name == 'customFilter') {
          if (initFilter == 0) {
            customFilterStr <<- gsub("[\r\n]", "", input$customFilter)
            initFilter <<- 1
            if (customFilterStr!=''){
              filterStr <<- paste(filterStr,' & ',customFilterStr,sep='')
              filterStrProd <<- paste(filterStrProd,' & ',customFilterStr, sep='')
            }
          } else{
            next 
          }

        } else if (grepl('Min$', name)) {
          field <- substr(name, 1, nchar(name)-3)
          expr <- paste(field,'>=',inputs[[name]])
          filterStr <<- paste(filterStr,expr,sep=' & ')
          filterStrProd <<- paste(filterStrProd,expr,sep=' & ')
        } else if (grepl('Max$', name)) {
          field <- substr(name, 1, nchar(name)-3)
          expr <- paste(field,'<=',inputs[[name]])
          filterStr <<- paste(filterStr,expr,sep=' & ')
          filterStrProd <<- paste(filterStrProd,expr,sep=' & ')
        } else {
          field <- name
          expr <- paste(field,'%in%',deparse(inputs[[name]],width.cutoff=500))
          filterStr <<- paste(filterStr,expr,sep=' & ')
          filterStrProd <<- paste(filterStrProd,expr,sep=' & ')
        }
      }

      filterStr <<- gsub('^ & ','',filterStr)
      filterStrProd <<- gsub('^ & ','',filterStrProd)
      
      if (customFilterStr!=''){
        filterStr <<- paste(filterStr,' & ',customFilterStr,sep='')
        filterStrProd <<- paste(filterStrProd,' & ',customFilterStr, sep='')
      }
      
      filterStr <<- gsub('^ & ','',filterStr)
      filterStrProd <<- gsub('^ & ','',filterStrProd)

      if (filterStr == '') filterStr <<- 'intRate > 0'
      if (filterStrProd == '') filterStrProd <<- 'intRate > 0'
      
      if(input$complete) {
        totalNotes <<- nrow(filter_(notes, '(complete==TRUE & (loan_status=="Fully_Paid" | loan_status=="Charged_Off"))'))
      } else { 
        totalNotes <<- nrow(notes)
      }
      
      
      
      # If filter is incorrect, then return empty table
      error <<- 0
      table <- tryCatch({
        filter_(notes, filterStr)
      },error = function(e) {
        error <<- 1
        data.frame()
      })

      
      
      
      

      if (nrow(table) > 0) {
        table <- group_by(table, grade) %>%
          summarise(averageROI=round(mean(ROI),2),
            projectedROI=round(mean(projROI),2),
            noteCount=n(),
            defCount=sum(isDef),
            l16Count=sum(isL16),
            l31Count=sum(isL31),
            ageMonths=round(mean(ageMths)) ) %>%
            # standardDeviation=round(sd(projROI),2) ) %>%
          mutate(percentNotes = round ( 100 * noteCount/sum(noteCount), 2) ) %>%
          mutate(percentDef = round ( 100 * defCount/noteCount, 2) ) %>%
          mutate(percentL16 = round ( 100 * l16Count/noteCount, 2) ) %>%
          mutate(percentL31 = round ( 100 * l31Count/noteCount, 2) )
        
      }
      table

    
    })
    
    output$text <- renderText({ 
      if (error==1) {
        'Error in filter:  Please check your filter syntax'
      } else if (nrow(dataInput())==0) {
        'No records found'
      } else {
        ''
       # print(dataInput())
      }
    })
    
    output$roi <- renderChart({ 
      di <- dataInput()
      if (nrow(di) > 0) {
        d=subset(melt(di, id = "grade"), variable %in% c('averageROI','projectedROI','percentDef'))
        h=hPlot(value ~ grade, data = d, group='variable', type = c('column','column','column'), title = "Return by Grade")
        h$plotOptions(column = list(colorByPoint = F, animation = list(duration=500)))
        h$xAxis(title = list(text = "Loan Grade"), categories = unique(d$grade))
        h$yAxis(title = list(text = "ROI"))
        h$addParams(dom = 'roi')
        # print(h)
        return(h)
      } else {
        emptyChart <- rCharts::Highcharts$new()
        emptyChart$chart(type = "gauge",height=1)
        emptyChart$addParams(dom = 'roi')
        return(emptyChart)
      }
    })
    
    output$count <- renderChart({
      di <- dataInput()
      if (nrow(di) > 0) {
        h=hPlot(value ~ grade, data = subset(melt(di, id = "grade"), variable %in% c('percentNotes')), group='variable', type = c('pie'), title = "Percent Distribution by Grade")
        h$plotOptions(pie = list(animation = list(duration=500)))
        h$addParams(dom = 'count')
        return(h)
      } else {
        emptyChart <- rCharts::Highcharts$new()
        emptyChart$chart(type = "gauge",height=1)
        emptyChart$addParams(dom = 'count')
        return(emptyChart)
      }
    })
    
    output$gaugeROI <- renderChart({ 
      di <<- dataInput()
      if (nrow(di)>0) {
        numNotes<<-round(sum(di$noteCount))
        roi<<-round(sum(di$averageROI*di$noteCount)/numNotes,2)
        if (roi<0) {
          color='#DF5353'
        } else {
          color='#55BF3B'
        }
        
        #pct=round(numNotes/totalNotes*100,2)
        proi=round(sum(di$projectedROI*di$noteCount)/numNotes,2)
        if (proi<0) {
          pcolor='#DF5353'
        } else {
          pcolor='#55BF3B'
        }
        
        maxROI = max(c(roi,proi))
        minROI = min(c(roi,proi))
        
        a <- rCharts::Highcharts$new()
        a$chart(type = "gauge",height=180)
        
        # a$title(text="Portfolio Performance")
        
        a$pane(
          list(startAngle=-90,endAngle=90,size=220,background=list(shape='arc'),center=list('25%','90%')),
          list(startAngle=-90,endAngle=90,size=220,background=list(shape='arc'),center=list('75%','90%'))
        )
        
        a$plotOptions(gauge = list(dataLabels=FALSE,
          animation = list(duration=700)))
        
        a$series(list(
          list(data = list(roi), name = "ROI", yAxis = 0, 
            pivot=list(backgroundColor=color), dial=list(backgroundColor=color)),
          list(data = list(proi), name = "Projected ROI", yAxis = 1,
            pivot=list(backgroundColor='#7cb5ec'), dial=list(backgroundColor=pcolor))))
        
        a$yAxis(list(
          list(title = list(text = "Instant ROI"), min = minROI-5, max=maxROI+5, pane=0),
          list(title = list(text = "Projected ROI"), min=minROI-5, max=maxROI+5, pane = 1)
        ))
        # more(a$print())
        
        a$addParams(dom = 'gaugeROI')
        return(a)
        
      } else {
        emptyChart <- rCharts::Highcharts$new()
        emptyChart$chart(type = "gauge",height=1)
        emptyChart$addParams(dom = 'gaugeROI')
        return(emptyChart)
      }
      
    })
    
    # Filter criteria 
    output$criteria <-renderUI({

      di=dataInput()

      f <- filterStrProd
      if(filterStrProd=='intRate > 0') f <- 'NA'
      
      fluidRow(
        wellPanel(
          strong("Filter: "),
          f
        )       
      )

    })
    
    # Summary
    output$summary <-renderUI({
      di=dataInput()
      # print(di)
      if (nrow(di)>0) {
        numNotes=round(sum(di$noteCount))
        pct=round(numNotes/totalNotes*100,2)
        roi=round(sum(di$averageROI*di$noteCount)/numNotes,2)
        # print(input$complete)
        proi=round(sum(di$projectedROI*di$noteCount)/numNotes,2)
        age=round(sum(di$ageMonths*di$noteCount)/numNotes)
        def=round(sum(di$percentDef*di$noteCount)/numNotes,2)
        l16=round(sum(di$percentL16*di$noteCount)/numNotes,2)
        l31=round(sum(di$percentL31*di$noteCount)/numNotes,2)
        fluidRow(
          # h4("Summary",style="font-family: 'verdana'; font-weight: 500; line-height: 1.2;", align='center'),
          wellPanel(
            fluidRow(
              column(4,paste('Total Notes:',printNumber(totalNotes))),
              column(4,paste('Filtered Notes:',printNumber(numNotes))),
              column(4,paste('Filtered Percent: ',pct,'%',sep=''))
            ),
            fluidRow(
              column(4,paste('Instant ROI: ',roi,'%',sep='')),
              column(4,paste('Projected ROI: ',proi,'%',sep='')),
              column(4,paste('Age Months:',age))
            ),
            fluidRow(
              column(4,paste('Default Percent: ',def,'%',sep='')),
              column(4,paste('Late 16: ',l16,'%',sep='')),
              column(4,paste('Late 31: ',l31,'%',sep=''))
            )
          )       
        )
      }
    })

    
  },
  options = list(launch.browser=launch.browser)
)